name: "Windows"
description: "Run lightweight Windows in Docker with browser-based access"
version: "1.0.0"
slug: "addon-windows"
url: "https://github.com/jessica12ryan/homesync-addons"

arch:
  - amd64
  
startup: "services"
panel: true
boot: "auto"

host_ipc: true

full_access: true

privileged:
  - SYS_ADMIN
  - NET_ADMIN
  - SYS_RAWIO
  - SYS_PTRACE
  - DAC_READ_SEARCH

map:
  - config:rw

ports:
  8006/tcp: 8006

ingress: true
ingress_port: 8006
panel_icon: "mdi:microsoft-windows"
webui: "http://[HOST]:[PORT:8006]"

options:
  KVM: "N"
  DISK_SIZE: "16G"
  VERSION: "11"
  LANGUAGE: "English"

schema:
  KVM: list(N|Y)
  DISK_SIZE: list(16G|32G|64G|128G)
  VERSION: list(11|10|xp)
  LANGUAGE: list(English|French)

environment:
  KVM: "!KVM"
  DISK_SIZE: "!DISK_SIZE"
  VERSION: "!VERSION"
  LANGUAGE: "!LANGUAGE"
