name: "Windows"
slug: "windows"
description: "Run lightweight Windows in Docker with browser-based access"
version: "1.0.0"
image: "jessica12ryan/{arch}-addon-windows"
arch:
  - amd64
startup: "services"
boot: "auto"
ingress: true
ingress_port: 80
panel_icon: "mdi:microsoft-windows"
host_network: false
host_ipc: true
privileged:
  - SYS_ADMIN
devices:
  - /dev/kvm:rmw
map:
  - config:rw
ports:
  6080/tcp: 6080
options:
  custom_port: 6080
schema:
  custom_port: port
