name: "Windows"
description: "Run lightweight Windows in Docker with browser-based access"
version: "1.0.0"
slug: "addon-windows"

arch:
  - amd64
  
startup: "services"
panel: true
boot: "auto"

host_network: true
host_ipc: true

full_access: true

privileged:
  - SYS_ADMIN
  - NET_ADMIN
  - SYS_RAWIO
  - SYS_PTRACE
  - DAC_READ_SEARCH

map:
  - config:rw

ingress: true
ingress_port: 8006
panel_icon: "mdi:microsoft-windows"
webui: "http://[HOST]:[PORT:8006]"
  
environment:
  KVM: "N"
  DISK_SIZE: "16G"
  VERSION: "xp"
  LANGUAGE: "English"
  USERNAME: "Docker"
  PASSWORD: "admin"
