name: "Windows"
description: "Run lightweight Windows in Docker with browser-based access"
version: "0.7.1"
slug: "addon-windows"
arch:
  - amd64
startup: "services"
panel: true
boot: "auto"
ingress: true
ingress_port: 8006
panel_icon: "mdi:microsoft-windows"
webui: "http://[HOST]:[PORT:8006]"
host_network: true
host_ipc: true
privileged:
  - SYS_ADMIN
  - NET_ADMIN
  - SYS_RAWIO
  - SYS_PTRACE
  - DAC_READ_SEARCH
full_access: true
map:
  - config:rw

devices:
  - /dev/kvm:/dev/kvm
environment:
  KVM: "${KVM:-Y}"
