name: "Windows"
description: "Run lightweight Windows in Docker with browser-based access"
version: "0.6.0"
slug: "windows"
arch:
  - amd64
startup: "services"
panel: true
boot: "auto"
ingress: true
ingress_port: 80
panel_icon: "mdi:microsoft-windows"
host_network: false
host_ipc: true
privileged:
  - SYS_ADMIN
  - NET_ADMIN
  - SYS_RAWIO
  - SYS_PTRACE
  - DAC_READ_SEARCH
full_access: true
map:
  - config:rw
ports:
  6080/tcp: 6080
