name: "FPP - Falcon Player"
description: "Falcon Player (FPP) is a lightweight, optimized, feature-rich sequence player."
version: "9.5"
slug: "addon-fpp"
url: "https://github.com/jessica12ryan/homesync-addons"

image: "falconchristmas/fpp"

arch:
  - amd64
  - aarch64
  
startup: "services"
boot: "auto"

host_network: true
host_ipc: true

ingress: true
ingress_port: 8099
panel_icon: mdi:led-strip-variant

full_access: true
map:
  - config:rw
  - media:rw
  - share:rw
