name: "FPP - Falcon Player"
description: "Falcon Player (FPP) is a lightweight, optimized, feature-rich sequence player."
version: "1.0"
slug: "addon-fpp"
url: "https://github.com/jessica12ryan/homesync-addons"

image: "falconchristmas/fpp:latest"

arch:
  - amd64
  - aarch64
  - armhf
  
startup: "services"
boot: "auto"

host_network: true
host_ipc: true

full_access: true
map:
  - config:rw
  - media:rw
  - share:rw

ingress: true
ingress_port: 80
panel_icon: mdi:led-strip-variant
