name: "FPP - Falcon Player"
description: "Falcon Player (FPP) is a lightweight, optimized, feature-rich sequence player"
version: "9.5.1"
slug: "addon-fpp"
url: "https://github.com/jessica12ryan/homesync-addons"

image: "ghcr.io/jessica12ryan/fpp_haos:latest"

arch:
  - amd64
  - aarch64
  - armhf
  
startup: "services"
boot: "auto"

host_network: true
host_ipc: true

full_access: true

options:
  fpp_data_path: "/config/fpp"

schema:
  fpp_data_path: str

ingress: true
ingress_port: 80
panel_icon: mdi:led-strip-variant
