name: "FPP - Falcon Player"
description: "Falcon Player (FPP) is a lightweight, optimized, feature-rich sequence player"
version: "master"
slug: "addon-fpp"
url: "https://github.com/jessica12ryan/homesync-addons"

image: "falconchristmas/fpp"

arch:
  - amd64
  - aarch64
  - armhf
  
startup: "services"
boot: "auto"

ports:
  80: 80
  4048/udp: 4048
  5568/udp: 5568
  32320/udp: 32320
  32322: 32322
  9000: 9000
  
ports_description:
    80: "HTTP",
    4048/udp: "DDP",
    5568/udp: "e1.31",
    32320/udp: "MultiSync",
    32322: "FPPD/HTTP",
    9000: "Other"

host_network: false
host_ipc: true

full_access: true

ingress: true
ingress_port: 80
panel_icon: mdi:led-strip-variant

map:
  - config:rw

environment:
  FPP_MEDIA_DIR: /home/fpp/media
