name: "FPP - Falcon Player"
description: "Run lightweight Windows in Docker with browser-based access"
version: "9.5"
slug: "addon-fpp"
url: "https://github.com"

image: "falconchristmas/fpp"

arch:
  - amd64
  - aarch64
  
startup: "services"
boot: "auto"

host_network: true
host_ipc: true

privileged: true

capabilities:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_PTRACE
  - DAC_READ_SEARCH

full_access: true
map:
  - config:rw
  - media:rw
  - share:rw
